// export const metadata = {
//   title: 'TricksterWeb',
//   description: 'Generated by Next.js',
// }

import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    // absolute: `replace title`,
    default: "TricksterWeb",
    template: "%s | TricksterWeb"
  },
  description: "Default Description"
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
